version: "3"
services:
  icecast:
    container_name: cc-venue_icecast_1
    image: moul/icecast:latest
    env_file:
      - project.env
    ports:
      - "8000:8000"
    networks:
      - dev
  
  # add https://hub.docker.com/_/eggdrop/ bot?
  irc:
    #container_name: cc-venue_irc_1
    image: inspircd/inspircd-docker:latest
    env_file:
      - project.env
    ports:
      - "6667:6667"
      - "6697:6697"
      - "7000:7000"
      - "7001:7001"
    networks:
      - dev
  
  db:
    container_name: cc-venue_db_1
    image: postgres:latest
    env_file:
      - project.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev
  
  irc-builder:
    container_name: cc-venue_ircbuilder_1
    build: ircclient_builder
    volumes:
      - ./vakten/vaktpj/guard/static/ircclient/:/bundle/
      - ./ircclient_builder/config.json:/config.json
  
  webircgateway:
    container_name: cc-venue_webircgateway_1
    build: webircgateway
    ports:
      - 8888:80
    networks:
      - dev
  
  vakten:
    container_name: cc-venue_vakten_1
    build: vakten/vaktpj/
    env_file:
      - project.env
    ports:
      - 8080:8080
    networks:
      - dev
    depends_on:
      - db
      - irc-builder
      - webircgateway
    volumes:
      - ./vakten/vaktpj:/code
      - staticfiles:/opt/staticfiles
  
  nginx:
    container_name: cc-venue_nginx_1
    image: nginx:mainline-alpine
    ports:
      - 1337:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/opt/staticfiles
    networks:
      - dev
    depends_on:
      - vakten
  
  jamulus:
    container_name: cc-venue_jamulus_1
    image: pakzer0/jamulus:alpine
    build: Jamulus/
    ports:
      - "22124:22124/udp"
    env_file:
      - project.env
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--welcomemessage"
      - "Welcome to the Jamulus rehearsal room"
      - "--numchannels"
      - "16"
      - "-d"
      - "-T"

networks:
  dev:

volumes:
  db-data:
  staticfiles:
