# Generated by Django 3.1.3 on 2020-12-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('mountpoint', models.CharField(max_length=128)),
                ('run_ads', models.BooleanField(default=False)),
                ('max_clients', models.IntegerField(default=50)),
                ('free_stream', models.BooleanField(default=True)),
                ('flexible_fee', models.BooleanField(default=True)),
                ('access_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('value', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guard.tokentype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
